### PR TITLE
Be ORM-agnostic - don't require ActiveRecord

### PR DESCRIPTION
**Pull request by k3rni**

### CODE REVIEW

**Comment by tomichj** [comment]
Hello @k3rni! It's like you read my mind; thanks very much for this contribution! I'll look through this sometime today and get back to you shortly.

**Comment by tomichj** [comment]
Thanks @k3rni!

**Comment by tomichj** [comment]
You've inspired me, I'm going to excise the dependency on ActiveSupport::Concern also.

**Comment by k3rni** [comment]
For me at least, AS is far less controversial than AR, and requiring it is not a big deal. An example project using one but not the other would be any Rails app with an alternative ORM, such as Sequel or ROM; or anything using Spring, Carrierwave, and many other popular gems.

That said, you only use AS for its convenient Concern module, and that can be replaced rather easily, because there are no tricky corners here. I say go for it :)

**Pull request merged**
